### ISSUE TITLE
Support automatic wrapping of MNT into WMNT, and then proceed to the WMNT approval process.

### ISSUE THREAD

**Issue by zkLinkLabs** [zkLinkProtocol/dapp-portal#29]
In the Mantle docs, you can find the contract address for WMNT.
https://docs.mantle.xyz/governance/parameters/tokenomics

**Comment by Evan-zkLinkLabs** [comment]
and WETH auto unwrap to ETH

**Comment by MickWang** [comment]
https://github.com/zkLinkProtocol/dapp-portal/pull/85
